### ISSUE TITLE
Compilation error due to struct "MQTTAsync_connectOptions"

### ISSUE THREAD

**Issue by xmanjimmy** [eclipse/paho.mqtt.cpp#119]
Hi folks, I was trying to compile paho cpp client from source:

https://github.com/eclipse/paho.mqtt.cpp

However, the code in file "connect_options.cpp" gives me compilation error, due to it is trying to access an nonexist member "*binarypwd*" in C struct "*MQTTAsync_connectOptions*".

Besides, it is trying to copy two "*MQTTAsync_connectOptions*" struct object by invoking "=" operator, however, this operator overload is not defined in that C struct (obviously cause it is **C** struct!)

This is weird, because the code should be well maintained on github, do I miss something in here?

Thanks!

**Comment by xmanjimmy** [comment]
BTW, the paho.mqtt.c source is from:

https://github.com/eclipse/paho.mqtt.c

**Comment by xmanjimmy** [comment]
Sorry I just found that it is not compatible with master branch of paho.mqtt.c 

I will try with development branch.

**Comment by fpagliughi** [comment]
Yes, the latest C++ library needs to be built against the 'develop' branch of the Paho C library, as noted at the top of the README.

It is probably best to be working with the 'develop' branch of the C++ library at this point as well, since it contains a few bug fixes.

Both libraries are due to be released in the next few weeks, from the code currently in the develop branches.

**Comment by xmanjimmy** [comment]
Thanks fpagliughi :)
