### ISSUE TITLE
Redundant methods connect_options::set_connect[ion]_timeout()

### ISSUE THREAD

**Issue by MartinGebert** [eclipse/paho.mqtt.cpp#152]
Both `mqtt::connect_options::set_connect_timeout()` and `mqtt::connect_options::set_connection_timeout()` set the member `opts_.connectTimeout`, while there's only `mqtt::connect_options::get_connect_timeout()` to retrieve it.

Proposal: Remove the sparsely documented `set_connection_timeout()` in favour of a symmetric setter/getter pair.

On a related note, the client features `mqtt::client::set_timeout()`, but the relation to the connection timeout is unclear - does one affect the other?

**Comment by fpagliughi** [comment]
Thanks for reporting this. That first one sounds like  a mistake. I will verify that it, then fix it and make it consistent. 

The connect_options are passed directly to the underlying C library to affect its behavior.

The C++ `client` object is synchronous and will block until an operation completes - any operation, including connect, disconnect, publish a message, etc. The `client::set_timeout()` sets the upper bound for all of those operations so that the application doesn't block and hang forever if one operation fails to complete. This is a user parameter since the value should be different depending on the underlying type of network and connection. (Higher for a satellite phone, lower for a LAN, perhaps).

The value is a wait timeout in the C++ wrapper library. If it fails, the operation could still silently complete some time later, So it is best to set this at a higher value and use it as a last resort.

There is a bit of a redundance in the connect options and the client timeout, but remember, too that the connect options are also used by the async_client.
