### ISSUE TITLE
Client times out with keep alive interval of 1s 

### ISSUE THREAD

**Issue by blues-breaker** [eclipse/paho.mqtt.cpp#165]
When connecting a client with a keep alive interval of one second the client does not seem to send PINGREQs at the required rate.

This results in the broker disconnecting the client.

Mosquito in verbose mode prints: `Client <client name> has exceeded timeout, disconnecting.`

I have used the Python Paho library to connect a client with 1s keep alive interval without issue.

Apologies if this is an problem with the underlying C library and this issue should be in the C project's tracker.

Please find attached test program to reproduce the issue.

[keep_alive_test.cpp.zip](https://github.com/eclipse/paho.mqtt.cpp/files/2643317/keep_alive_test.cpp.zip)

**Comment by fpagliughi** [comment]
No worries about creating the issue here. The C library is responsible for actually putting all traffic on the wire, but we can first look that 
 1. We're properly sending the correct parameters to the library, and
 2. That it hasn't already been fixed in a newer version of the C library than we're using.
If we can fix it in the C++ library, that's the easiest solution, otherwise we can raise the issue in the C lib.

**Comment by blues-breaker** [comment]
Thanks for the reply.

I have reproduced the issue using a C client and so I guess the issue must be with the underlying C library.

I have created an issue in the C project's tracker.

**Comment by fpagliughi** [comment]
Cross-link for easy reference:
https://github.com/eclipse/paho.mqtt.c/issues/590

**Comment by fpagliughi** [comment]
It's being fixed in the Paho C library.
