### ISSUE TITLE
Subscriber can't receive messages after reconnection

### ISSUE THREAD

**Issue by 123AWS7** [eclipse/paho.mqtt.cpp#171]
I built a publisher and subscriber sample code, the publisher publish every 1 second and the subscriber receives and prints them but when the connection to broker lost and back again the subscriber reconnects to the broker and connect successfully BUT it can't receive anything, should I subscribe again to be able to receive messages ?

**Comment by fpagliughi** [comment]
It depends on what "clean session" option that you're sending to the server on connection. 
 - If you set clean session to `true`, it tells the server to forget anything about your client and start fresh. This includes any previous subscriptions.
 - If you set clean session to `false`, then it tells the server that you want a persistent session, and it should keep information about your client when it disconnects, This includes any active subscriptions. It will also save the messages that match those descriptions when your client is off-line.

When you use persistent subscriptions, you are required to use unique client ID's for your applications so that the server can track them individually. You shouldn't use blank client ID's in that case.
