### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by MattiasEppler** [eclipse/paho.mqtt.cpp#206]
Nothing worse then building your own assemblies with sourcecode from other coders :-).

I created 2 nugetpackages for windows compiled with vs 2017
paho.mqtt.c
paho.mqtt.cpp

Is it ok if I upload this packages on nuget.org.
So other users can simply download and use.

What about licenses?

**Comment by fpagliughi** [comment]
Huh. I have no idea. It would definitely be helpful, but at a bare minimum we would need to know how it's done to keep it updated after you disappear :-)  And also make sure that it's useful for people and easy enough to maintain after you're gone. 
I suggest that you post the same request on the Paho C page since we're also talking about that project. If Ian, the maintainer of that project OK's it, then I would be OK as well.

**Comment by MattiasEppler** [comment]
Hi. 
I created the nugetpackage manualy with NuGet Package Explorer
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer

But create it automaticaly is even nicer. Anyway if you update your source and create a new release in short intervals.

In c# its easy to create it automaticaly:
https://docs.microsoft.com/de-de/nuget/create-packages/creating-a-package

In c++ its also possible:
https://devblogs.microsoft.com/cppblog/nuget-for-c/

The articel refers to coapp:
http://coapp.org/tutorials/building-a-package.html

But it looks not to be up to date.

Requirements:
   Windows Vista, Windows 7, or Windows 8 
   Visual Studio 2012 or 2010

Hm...

**Comment by ciprian90** [comment]
+1 for cpp nuget, please :)
