### ISSUE TITLE
Unresolved external symbol Log when building on Windows x64

### ISSUE THREAD

**Issue by MarcoGrochowski** [eclipse/paho.mqtt.cpp#211]
Unresolved external symbol Log error after commit:
`https://github.com/eclipse/paho.mqtt.cpp/commit/df7761f8fd59d9af8645556fac132e7ed146f571#diff-584915ab2d8e59491d23dec877c44059`
when trying to build the shared library, the static library is able to build but gives linker errors .

**Comment by KrYpToDeN** [comment]
The same error.
Did you find the way to solve it?

**Comment by fpagliughi** [comment]
This is the same as #223.

Basically, _Log()_ is a function in the Paho C library. Calls to it were recently added to this C++ library so that the combined library would log to the same place and intermix nicely.

On Linux the guess was that some people were using the old Makefile for the Paho C library and that it was not compiling in the Log function. Rebuilding the C lib with cmake seemed to fix the problem there.

I don't know the issue in Windows, and can look into it. In the meantime, for a quick fix, the Log calls are definitely not required in the C++ library.  You can just log them out or delete them before compiling the C++ lib. There are about six calls from _async_client.cpp_ and _token.cpp_.

**Comment by smarty70** [comment]
I solved the Problem:

- By CMake in line PAHO_C_LIBARIES I put all c libaries separated with semicolon into it
(c:\...\paho-mqtt3a.lib; c:\...\paho-mqtt3c.lib)

- In Visual Studio I changed/controlled from paho-mqttpp3 the properties->linker->input->additional dependencies and there must be semicolons between the libs and not %B

**Comment by fpagliughi** [comment]
To my knowledge, you don't need to link to the synchronous Paho C library (paho-mqtt3c.lib).

You only need to link to one of the asynchronous libraries:
`paho-mqtt3a.lib` for unsecure connections, or
`paho-mqtt3as.lib` for secure connections using SSL

Is the `Log()` function in the synchronous library?

**Comment by smarty70** [comment]
important for the log function is the "common_obj.lib"

**Comment by fpagliughi** [comment]
Apparently the Log() function in the Paho C lib was meant to be private to that library and should not have been used. It is being removed from the C++ lib.

See also #223, #235.

**Comment by thalionath** [comment]
As a workaround, you could provide an implementation in your application instead of linking against common_obj.lib

```
extern "C" {
    enum LOG_LEVELS {};
    void Log(enum LOG_LEVELS, int, const char *, ...) {}
}
```

**Comment by fpagliughi** [comment]
Yes, apologies that the fix went into master a while ago, but the new release it not ready yet.
