### ISSUE TITLE
mqttcpp -> server response error

### ISSUE THREAD

**Issue by RamakrishnanOSS** [eclipse/paho.mqtt.cpp#224]
I always receive the following error while subscribing a set of topics.

subscribeToTopicList()
{
std::vector < string > topicList; // list of string
std::vector< int > qosList; // Contains same no.of elements as topicList and the contents is 1.
mqtt::const_string_collection_ptr topicColl = mqtt::string_collection::create(topicList);
 mqtt::token_ptr subTok = mqttClient->subscribe(topicColl, qosList);
subTok->wait_for({ 1000 });
}

What could be the issue?

Thread 3 "sample-applicat" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeff18700 (LWP 89942)]
0x00007ffff52ac6ef in mqtt::subscribe_response::subscribe_response (this=0x7fffe8001740, n=1, rsp=0x7fffeff17e30)
    at /mnt/hgfs/AgriFSP/fcal/Dependencies/paho.mqtt.cpp/src/mqtt/server_response.h:142
142					reasonCodes_.push_back(ReasonCode(rsp->alt.qosList[i]));

**Comment by fpagliughi** [comment]
OK. It appears that there's a bug in the C++ lib when subscribing using a collection, but the collection only has one item. The response comes back with the item in a different place than expected. The array of responses is NULL. I'll get this fixed ASAP.

**Comment by Pascal-Fremaux** [comment]
Hi,

We confirm this issue, due to documentation API error in Paho C: 
MQTTAsync_subscribeMany() can be used with a collection of 1 item (in fact, this is the implementation of MQTTAsync_subscribe() ). But it returns the data in alt.qos , as described when using API MQTTAsync_subscribe(). Not in the array alt.qosList, as described for API MQTTAsync_subscribeMany() (the attribute diff probably come from trouble with the usage of C union and compiler optimisations that force them to use 2 differents attributes). 
alt.qosList in this case is not NULL (happen only on DEBUG mode), but uninitialized, which cause seg fault errors.

In Paho CPP we have solved the issue in Paho CPP by replacing in subscribe_response() constructor for MQTT v3 the check for n==0 by n==1, and check the other branch >1 (to safety and explicitely remove negative and 0 case), and of course use the value 1 in place of 0 for the subscribe APIs with one element.

(in server_response.h)
```
	subscribe_response(size_t n, MQTTAsync_successData* rsp) {
		if (n == 1)
			reasonCodes_.push_back(ReasonCode(rsp->alt.qos));
		else if (n > 1)
			for (size_t i=0; i<n; ++i)
				reasonCodes_.push_back(ReasonCode(rsp->alt.qosList[i]));
	}
```
(in subcribe methods)
```
	-tok->set_num_expected(0);	// Indicates non-array response for single val
	+tok->set_num_expected(1);
```


A simple workaround is also obviously **not using the subscribe collection when having a unique topic**, but it is not documented to avoid that.

**Comment by Pascal-Fremaux** [comment]
In addition, the calls to set_num_expected() seems useless !

**Comment by fpagliughi** [comment]
Yes. Sorry. I fixed the Rust client a while ago for this same issue, but haven't had time to get back to the C++ client yet. It will be there in the next release.

**Comment by gocarlos** [comment]
close issue?

**Comment by fpagliughi** [comment]
Sure. I left it open until I got a confirmation or pushed into a release, but if you think it's working, I can close this.
