### ISSUE TITLE
Getting 'MQTT error [-1]: TCP connect completion failure' error while connecting to broker using SSL certificates

### ISSUE THREAD

**Issue by jadhavshital** [eclipse/paho.mqtt.cpp#234]
Hi,
I have tested the sample 'paho.mqtt.cpp/src/samples/ssl_publish.cpp' code it is working in Linux.
But when I try to connect with other mqtt broker with certificates I get following error:-
![publisher_error](https://user-images.githubusercontent.com/17235485/71664189-10d8e300-2d7e-11ea-8937-e46947244f1b.PNG)

I am using broker address as follows:- 
`some_virtual_machine's_dns_address:8883`

I am using Client certificate file and client private file. To pass these files following function are using :- `sslopts.set_key_store("./client_cert_file.pem.crt")`
`sslopts.set_private_key("./client_key_file.pem.key")`

I don't have CA file so I am skipping 'sslsopts.set_trust_strore()' method.
But in this repository sample code, they have only use following function :- 
`sslopts.set_trust_store("./ca_file.crt")`
`sslopts.set_key_store("./client_cert_file.pem")`

Is there issue with certificates or something else?
Kindly suggest some solution to resolve this issue.

**Comment by saftkran** [comment]
I think there is a lot of confusion around these features. I have the same problem when I try to use the ssl_options.ca_path() method to pass a path to a directory containing my CA certs. I think this method would be better than set_trust_store, since set_trust_store requires you to concatenate all your CA certs into a single file.

Anyway, for your problem, since you you're not going to use a CA cert to authenticate the identity of the broker, you can use ssl_options.set_enable_server_cert_auth() and call it with false to tell paho to not bother trying to authenticate the broker. You can still use TLS encrypted communication this way, but without any authentication.

**Comment by lucvrgdias** [comment]
I was having the same problem. I fixed this by adding ssl:// to the url. Try with ssl://some_virtual_machine's_dns_address:8883

**Comment by fpagliughi** [comment]
PRs for documentation gladly accepted! :-)

**Comment by Yan-prrt** [comment]
> 我遇到了同样的问题。我通过在 URL 中添加 ssl:// 解决了这个问题。尝试使用 ssl://some_virtual_machine's_dns_address:8883

This is really very helpful to me. It's this problem that has been bothering me all day. Change TCP://to SSL://
