### ISSUE TITLE
Expose paho.mqtt.c 1.3.6 new features

### ISSUE THREAD

**Issue by keysight-daryl** [eclipse/paho.mqtt.cpp#296]
I cannot off the top of my head remember all the latest changes but @icraggs might be able to offer better information.  A few of the important new features need exposed through the C++ wrapper that I can remember are...
 - Persistence callbacks for encrypt/decrypt
 - Persistence options for purging of oldest messages
 - Callbacks for reconnect re-auth (expired token)
 - Create/connect new options

**Comment by icraggs** [comment]
The issues addressed in 1.3.6 are here: https://github.com/eclipse/paho.mqtt.c/milestone/11?closed=1

**Comment by fpagliughi** [comment]
The persistence callbacks to encrypt and decrypt the stored data turned out to be a bit unwieldy to wrap, and when combined with user-defined persistence, caused a performance hit by making two round trips in and out of the C library, with separate C memory allocations and deallocations each trip, which the C lib may not entirely support yet.

The same functionality can be added with the user-persistence callbacks. It seems like a better idea to implement a simple file persistence sample (via user-persistence) and let that serve as example on how people can tweak it for their own needs.

I started it here:
https://github.com/eclipse/paho.mqtt.cpp/blob/6e1444155c332f18841fd82ebe591e8ace570b0e/src/samples/data_publish.cpp#L83-L211
