### ISSUE TITLE
Reconnect to different address?

### ISSUE THREAD

**Issue by phuongtran7** [eclipse/paho.mqtt.cpp#346]
Hi,

Is there any way to config the client to pick a new random address to reconnect to if it gets disconnected with the first one somehow? I have a very simple cluster of RabbitMQ broker with MQTT plugin enable and I'd love to be able to switch between them if one of the broker goes down.

I tried looking through the `async_client` constructor and it seems that none of them accept multiple URI and the `connect` method also doesn't accept any new URI argument.

Thank you so much for your time and help.

**Comment by fpagliughi** [comment]
Yes, this was an add-on in the C library a few years ago, and for some odd reason it was placed into the _connect_ options instead of the _create_ options with the original URI.  The C++ library wraps the create options with the client class constructors, and wraps the _connect_ options with the `connect_options` class.

The `connect_options::set_servers()` will do what you want. You can give it a collection (like a vector) of strings. Each can be a full URI and can even use different protocols (tcp, ssl/tls; websockets) if you want.

Sorry, it could probably be documented better!

**Comment by phuongtran7** [comment]
Thank you so much for the info.

I was able to try the `connect_options::set_servers()` and everything worked as expected. However, there are something that still a bit unclear for me. Should the original address, address that passed when constructing the `async_client` also be inside the vector of the server address that is passed into the `set_servers`?

Also, in my test, it took around 30 seconds from the disconnect to reconnect to another address. Seems a bit long, is it because the `auto_reconnect` tries the first address first when the client disconnected, then other addresses later when that still doesn't work? If that the case can we tell the client to switch to new address as soon as the first one disconnect?

Thank you so much for your time and help.
