### ISSUE TITLE
Mqtt C++ build procedure for Raspberry Pi

### ISSUE THREAD

**Issue by yuvarajvelumani** [eclipse/paho.mqtt.cpp#375]
Hi,

I need clear instruction for build paho.mqtt.cpp for RaspberryPi.
I had same instruction as per paho.mqtt.c by copying the `toolchain.linux-arm11.cmake` to cmake folder.
I am using the below cmake command
cmake -GNinja -DPAHO_BUILD_SAMPLES=TRUE -DPAHO_BUILD_SHARED=ON -DPAHO_WITH_SSL=OFF -DPAHO_BUILD_STATIC=OFF -DCMAKE_TOOLCHAIN_FILE=~/paho.mqtt.cpp/cmake/toolchain.linux-arm11.cmake

But I don't see any makefile to build the project.
Kindly help.

**Comment by juanmartincas** [comment]
Hi! when I installed the library I did no used any makefile, check the paths /usr/local/lib/aarch64-linux-gnu to check if the so files are there, and /usr/local/include

In any case, i just followed the instructions on the README

**Comment by fpagliughi** [comment]
Since you configured like this:

> cmake -GNinja ...

you requested the Ninja generator, and as-per your request it created a `build.ninja` file and _not_ a Makefile. To build, run `ninja` (not make).

If you want a makefile, use the "Unix Makefiles" generator, or don't specify any `-G` generator, as Makefiles are the default on Linux.
