### ISSUE TITLE
MQTT Error [-6] Invalid Null reference

### ISSUE THREAD

**Issue by juamarCas** [eclipse/paho.mqtt.cpp#386]
Hi everyone!

I'm creating a class using paho mqtt cpp library called MQTTClient using protocol _wss_, but when i run the project i always get this error: _MQTT error [-6]: Invalid (NULL) parameter_ to put some context this is the constructor: 

```C++
 MQTTClient(const std::string& host, const std::string& port, const std::string& protocol):m_host(host), 
    m_port(port), m_protocol(protocol){
        m_url = m_protocol + "://" + m_host + ":" + m_port;
        m_conOpt = new mqtt::connect_options();
 }
```
In the constructor I just create the connect options object.
 I have another method called Connect(): 

```C++
void MQTTClient::Connect(const std::string& Client_ID){
    m_conOpt->set_keep_alive_interval(20);
    m_conOpt->set_clean_session(true);
    user_callback cb;

    m_persist = new sample_mem_persistence();

    m_client = new mqtt::client(m_url, Client_ID, m_persist);
    
    m_client->set_callback(cb);

    try{
        m_client->connect(*m_conOpt);
    }catch(const mqtt::exception& exc){
        std::cout<<exc<<std::endl;
    }
}
```
the persist variable and callback variable were created following some samples paho has in their library.

and this is how i call it from main:

```C++
#include <iostream>
#include "MQTTClient.h"

int main(int argv, const char ** argc){

    const std::string host     = "******";
    const std::string port     = "******";
    const std::string protocol = "wss";

    MQTTClient mqttClient (host, port, protocol);
    mqttClient.Connect("sssss");
    while(1){

    }
    return 0;
}
```

Any help would be appreciated. 
Thanks a lot

**Comment by fpagliughi** [comment]
The underlying C library is complaining that something in a struct provided to it (like the connect options) contains a NULL value in a field that it expects to be populated. This is mostly hidden from users of the C++ library, which takes care to properly populate the structures that it passes down, but there are a few instances where it can happen.

The most common is when a secure connection is requested via the server URI ("ssl://..." or "wss://..."), but then no SSL options are given to the connect options. I really should intercept that condition and return a better error message, because I still do that myself sometimes!

That appears to be the case here, with a request for the "wss" protocol, but no SSL options?

The value from the default SSL options constructor, `ssl_options()` should be enough to get past the [-6] error, like:
```
m_connOpt->set_ssl(ssl_options());
...
```
But I don't know if this would have the adequate parameters to connect to your server. Tweak it as you need.

**Comment by juamarCas** [comment]
@fpagliughi Thanks a lot! I started moving around the library and tested other options (tcp, ws, etc..) and it worked pretty well.
