### ISSUE TITLE
Does the cpp library implement automatic re-publishing of messages?

### ISSUE THREAD

**Issue by DocDriven** [eclipse/paho.mqtt.cpp#391]
My question refers to the topic of handling unsuccessfully publishing messages from client to broker in case QoS > 0.

As I understand it, QoS = 1 and 2 require the broker to send a PUBACK message to the client, which then triggers the 'delivery_completed' callback. When the answer has been received, the corresponding client token referring to the sending action is given to the callback and deleted afterwards.

At this point arises the question, how the user has to handle messages that could not be sent successfully to the broker. Do I have to manually keep track of all tokens and re-publish the corresponding messages if needed to make sure it arrives? Or is this already done under the hood by the C++ paho lib?

In the documentation I found the header for the client persistence (https://www.eclipse.org/paho/files/cppdoc/iclient__persistence_8h_source.html), but I am not sure if this behavior is enabled per default or if I have to specify this explicitly. I would assume that it is enabled and has to be touched only to tweak the desired behavior. However, there are seemingly no callbacks that can be customized when a publish succeeds/fails.

**Comment by fpagliughi** [comment]
Apologies this went missed, as I didn't have much time for the library at the time. But I will put the answer here now for completeness if anyone comes looking...

Yes, this library, and most MQTT libraries for that matter, will handle retries, mostly because the rules for retrying are explicitly stated in the specification and perhaps a little odd, as noted here in the v5 spec:

> 4.4 Message delivery retry
> When a Client reconnects with Clean Start set to 0 and a session is present, both the Client and Server MUST resend any unacknowledged PUBLISH packets (where QoS > 0) and PUBREL packets using their original Packet Identifiers. This is the only circumstance where a Client or Server is REQUIRED to resend messages. Clients and Servers MUST NOT resend messages at any other time [MQTT-4.4.0-1].

The basis for this is the fact that MQTT is required to ride on top of a reliable transport, so it is assumed that the messages will always be delivered by the underlying retries, etc, until and unless a disconnection happens. At that point, all assumptions are thrown away, and any incomplete transactions can (and MUST) be retried. But they will only be retried if a persistent session was established before, and then re-established the disconnect. Otherwise, if restarting with a clean start/session, the partially-completed transactions are discarded.
