### ISSUE TITLE
exc.get_reason_code() return 0 on catch -1 (in case of MQTTVERSION_5 usage)

### ISSUE THREAD

**Issue by Hadatko** [eclipse/paho.mqtt.cpp#409]
Hi,
code bellow looks like bug. (btw i am missing ":" between port and ip, so it should be easy to reproduce, the behavior is same for correct client address with tcp/tls connection error. )

```C++
m_client = std::unique_ptr<client>(new client(serverAddress, topic, create_options(MQTTVERSION_5)));

  auto connOpts = connect_options_builder()
                      .mqtt_version(MQTTVERSION_5)
                      .automatic_reconnect(chrono::seconds(2), chrono::seconds(30))
                      .clean_session(false)
                      .finalize();

  m_client->start_consuming();

  try
  {
      connect_response rsp = m_client->connect(connOpts);

      if (!rsp.is_session_present())
      {
          properties props{
              { property::SUBSCRIPTION_IDENTIFIER, 1 },
          };
          m_client->subscribe(topic, s_QOS, subOpts, props);
      }
  }
  catch (const mqtt::exception &exc)
  {
      // TODO: replace with Logger
      std::cerr << "\r\nError: " << exc.what() << " [" << exc.get_reason_code() << "]" << std::endl;
      err = ErrMqttInit;
  }
```

returns Error: MQTT error [-1] [0]

When i remove both usage of `MQTTVERSION_5` then error is Error: MQTT error [-1] [-1]

**Comment by fpagliughi** [comment]
The "reason code" is an MQTT v5 protocol value. It's a value that the _server_ (broker) sends back to you if it detects an error in the protocol. In earlier versions (v3.x) of the protocol, if the server was unhappy the only thing it could do was disconnect the client. And you would have no idea why it did so! The "reason code" gives the server the ability to tell you why it disconnected you.

So this is a value that the broker would send to you. If you are not connecting to the broker, perhaps because the URI is incorrect, then there is no "reason code" and you see a zero. The library does not try to fill it in with anything.

That said, if you turn off v5, then the older (v3.x) protocol does not have reason codes and the -1 you get is just an artificial filler from the library that you (probably) always get. You should not use the reason code when making a v3.x connection.

**Comment by Hadatko** [comment]
Hi, thank you very much for explanation. So i am closing issue. I was just confused that -1 and 0 in same output. I thought that they should be same.
