### ISSUE TITLE
Wrong return value of mqtt::client::try_consume_message_for() when it disconnects

### ISSUE THREAD

**Issue by Naslow** [eclipse/paho.mqtt.cpp#414]
Hello,

I use the mqtt::client to connect to an MQTT broker and then, in a different thread, I call regularly the function `client.try_consume_message_for(&message_ptr, std::chrono::seconds{1})`. If the function returns false, I attempt a reconnect and if it returns true, I handle the message. Now if the broker disconnect remotely and the client is currently within the call `try_consume_message_for`, the call returns with the value `true` and with `message_ptr` set to `nullptr`. I think, the call should return with false if the `message_ptr` value is not set (or set to `nullptr`). The next call(s) to `try_consume_message_for` returns `false` as expected.
Rough example:
```
class MyClass {
   void MyClass(mqtt::connect_options options) {
      client_ = std::make_unique<mqtt::client>("host", "client_id");
      client_->start_consuming();

      client_->connect(options);
      thread_ = std::thread {
         mqtt::const_message_ptr mqtt_message;
         while (true) {
            if (!client_->try_consume_message_for(&mqtt_message, std::chrono::seconds{1})) {
                 print("disconnected... attempt reconnect");
                 // add code to reconnect
                 continue;
             }
             
              auto payload = mqtt_message->get_payload(); // this crashes on disconnect since try_consume_message_for returned true
         }
      };
   }

   std::unique_ptr<mqtt::client> client_;
   std::thread thread_;
}
```

**Comment by fpagliughi** [comment]
Yeah, admittedly, this is a little weird.

The `try_...` function returns false if no message is received within the timeout time. Then you know that call timed out. The duration has passed (1sec, in your case), no message arrived, and the connection _is still open._

If you get a `true` return, but a null message pointer, then you know the connection was closed. This may have happened in less time than the wait duration.

If you get a `true` return and non-null message, then you got a message.

So, though a little strange, you can determine what happened from these combinations.

If I were to return `false` when the connection closed, the message would be null either way, and you wouldn't know if the wait timed out (and the connection is still open) or if the connection closed. 

So for now, I will leave it the way it is.

In the longer run, it would be nicer to pass one of several possible conditions through the consumer queue in an easier fashion I think at least these:
- A message, when received.
- A disconnect message (at least properties and reason code)
- Connection lost (instead of an empty message)
- Connection restored (if auto reconnect set up)

This would be a breaking API change, so would probably wait until bumping the library to v2.0. At that point moving to C++17 and having the return value be a _std::variant_ of these possible types would make sense.

But, like I said, for now I will leave it the way it is.
