### ISSUE TITLE
Undefined reference to "uuid_generate"

### ISSUE THREAD

**Issue by zambranohally** [eclipse/paho.mqtt.cpp#437]
Hi guys. Can someone help me with this issue.
I am using cmake with vcpkg in visual studio
![image](https://github.com/eclipse/paho.mqtt.cpp/assets/63218980/cedd50af-0b78-4ac9-bcb7-6ac8e37332e6)

**Comment by fpagliughi** [comment]
I see a call to `uui_generate` in the underlying Paho C library for WebSocket support. It appears to be a Linux system call. But that shouldn't be getting compiled in on Windows.

Maybe show your full build commands. And please copy/paste the text from the console window. Don't use images.

**Comment by zambranohally** [comment]
@fpagliughi
This is a cmake project in visual studio with wsl.
when building with visual studio, I got the error shown above.
When I manually run the build in wsl, still the same. Please refer below console output

`root@xxxx:/mnt/c/Users/xxxx# cmake --build /root/.vs/xxx/out/build/linux-debug --target xxx--config Debug
[1/1] Linking CXX executable xxx
FAILED: xxx
: && /usr/bin/g++ -g  CMakeFiles/xxx.dir/sources/vianad.cpp.o CMakeFiles/xxx.dir/sources/db_config.cpp.o CMakeFiles/xxx.dir/sources/api.cpp.o CMakeFiles/xxx.dir/sources/options.cpp.o CMakeFiles/xxx.dir/sources/cli.cpp.o CMakeFiles/xxx.dir/sources/m_device.cpp.o CMakeFiles/vianad.dir/sources/heartbeat.cpp.o CMakeFiles/xxx.dir/sources/m_heartbeat.cpp.o CMakeFiles/vianad.dir/sources/device.cpp.o CMakeFiles/xxx.dir/sources/camera.cpp.o CMakeFiles/vianad.dir/sources/m_camera.cpp.o CMakeFiles/xxx.dir/sources/m_rss_payload.cpp.o CMakeFiles/vianad.dir/sources/mqtt.cpp.o -o xxx /mnt/e/vcpkg/installed/x64-linux/debug/lib/libboost_program_options.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libspdlogd.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libpaho-mqttpp3.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libfmtd.a  -lstdc++  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libpaho-mqtt3as.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libpaho-mqtt3cs.a  -lc  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libssl.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libcrypto.a  -lpthread  -ldl  -lpthread  -lrt  -lanl && :
/usr/bin/ld: /mnt/e/vcpkg/installed/x64-linux/debug/lib/libpaho-mqtt3as.a(WebSocket.c.o): in function `WebSocket_connect':
/mnt/e/vcpkg/buildtrees/paho-mqtt/src/v1.3.12-bac1dc6114.clean/src/WebSocket.c:413: undefined reference to `uuid_generate'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.` 

Also when I manually run the build in actual ubuntu. Still the same error occur.
What could be wrong? Please can you help me with this. Thank you so much

**Comment by fpagliughi** [comment]
Apologies, I'm not much of a Windows programmer and had to look up what "WSL" is.

It seems that, perhaps, UUID support is not installed on WSL?

On Ubuntu, Paho C has always "just built fine" for me, but looking into it, perhaps the UUID support for WebSockets is through an additional library/package which just happened to be installed on my machine(s)? It looks like, maybe package `uuid-dev` is required? As in:
```
$ sudo apt install uuid-dev
```
But that doesn't make sense because no uuid library is being explicitly linked in to Paho C and it builds for me. The man page on Linux also claims, "libuuid  is part of the util-linux package since version 2.15.1":

https://man7.org/linux/man-pages/man3/uuid_generate.3.html

So, it it's missing from WSL, I have no idea how to add it. Can you install arbitrary libraries on WSL? That might work, but you might need to add an explicit dependency to your CMake.

**Comment by zambranohally** [comment]
@fpagliughi thank you so much for this
I tried all your recommendations but still no luck on my end.

But just a while ago I did some update in cmakelists.txt
I added this to target_link_libraries
`eclipse-paho-mqtt-c::paho-mqtt3as-static uuid`
and it works. build error no more

**Comment by fpagliughi** [comment]
Great
