### ISSUE TITLE
[Suggestion] File wildcards for CMake or autools

### ISSUE THREAD

**Issue by fpagliughi** [eclipse/paho.mqtt.cpp#88]
Is it possible to use file wildcards in the CMake and autotools builds? I think we can make the following assumptions:

- All source files in src should be built into the library (src/*.cpp)
- All header files in src/mqtt should be installed (src/mqtt/*.h)
- All the samples in src/samples should be built and installed when samples requested (src/samples/*.cpp)

The only complication is which of these should be excluded if SSL is not opted.

@guilhermeferreira

**Comment by guilhermeferreira** [comment]
Hello @fpagliughi,

Yes, it's feasible to use wildcards to collect files with the same extension in a variable. If found two methods so far, [file](https://cmake.org/cmake/help/v2.8.12/cmake.html#command:file) and [aux_source_directory](https://cmake.org/cmake/help/v2.8.12/cmake.html#command:aux_source_directory). However, both have the same drawback. According to the CMake documentation, they require one to rerun CMake in order to notice any file addition or removal.

Listing each file, if you change the `CMakeLists.txt`, it triggers a recompilation. On the other hand, if you use wildcards, no recompilation is triggered. This happens because the `CMakeLists.txt` does not change.

You can check this thread http://stackoverflow.com/questions/2110795/how-to-find-all-c-files-for-cmake-build-system

**Comment by guilhermeferreira** [comment]
Autotools does not have direct support for wildcards. It relies on GNU-Make. That's because Autotools possess some objections to the use of [wildcards](https://www.gnu.org/software/automake/manual/html_node/Wildcards.htmll).

The two major objections are:
- Include/omit files by mistake.
- Wildcards are not portable to some non-GNU make implementations

**Comment by fpagliughi** [comment]
Is this worth pursuing or should we just forget about it for now?
I think I've gotten the hang of adding and removing files from all the build systems, and once things settle down in a week or two, this won't be a big issue for a while.

**Comment by guilhermeferreira** [comment]
@fpagliughi the official documentation of both CMake and GNU Autotools recommend avoiding the wildcard approach. Also, if you look at forums, users say the same.

IMHO, adding wildcard support might cause more troubles than benefits:
- It's less error prone to list the files. Although we might forget to list a specific file, using wildcards we risk not include a bunch of files if we get the wildcard wrong.
- It's simpler to list the files. Including wildcard support is more complex than listing files, especially in the Autotools. Also, the addition/removal of files is not done very often.

There's another approach too. We can use a git hook to detect if a new file is listed in the `Makefile.am` and `CMakeLists.txt`. The advantage of this approach is that it uses the same shell script language instead of specific Autotools' or CMake's idiosyncrasies.

What do you think?

**Comment by fpagliughi** [comment]
I wasn't looking to get fancy. It's pretty simple to use wildcards with GNU Make, and I typically lay out my directories such that they can be compiled with that assumption... all library sources here, all public headers there, etc. 

I'll just close this one.
