### ISSUE TITLE
SSL support detection on compile-time or run-time?

### ISSUE THREAD

**Issue by guilhermeferreira** [eclipse/paho.mqtt.cpp#93]
Or... do we replace the SSL conditional compilation by an exception throw mechanism?

As we do not have an active mailing list, I decided to gather ideas here.

Currently, the SSL support in Paho MQTT C++ is done at compile-time. And it depends on which kind of Paho MQTT C library is available. If the user has the **libpaho-mqtt3as**, it might use (or not) the SSL. The user has this choice during the build. Otherwise, if there is only the **libpaho-mqtt3a** available, the user has no choice but do not use SSL.

**Conditional Compilation**

The major problems with the current approach are:
- Complicates the building system.
- Code polluted with `ifdefs`.
- Difficult the source code maintenance.
- _Might_ cause data conversion issues between C++ and C libraries. Like @fpagliughi said in #74, 
> If we compile out OPENSSL support, but link to the Paho C library that has SSL support, will there be any problems? Is there any way to mess up the structures passed to the C lib?
- Program crash if the application and the library don't agree on whether or not to use SSL (#76) 

In the end, the SSL support in Paho MQTT C++ should not be a build option. It should be decided automatically based on the Paho MQTT C library available.

**Exception Throw**

This approach has its drawbacks too. Some of them are:
- Force the user to handle an extra kind of exception.
- Postpone to run-time errors that could be detected at compile-time.
- Require many parts of the library to be _exception-safe_ and use exception-safe methods and containers.

**Comment by fpagliughi** [comment]
I'm in favor of removing the conditional compilation for SSL and always including the code. It doesn't directly call any OpenSSL functions, and so doesn't directly depend on the presence or absence of the SSL libraries on the system. And the additional code only adds ~10kB to the library binary on my Linux system.

I submitted a pull request to the Paho C library to return a specific error code from the non-SSL version of the library if the caller requests an SSL connection. So our code would be trivial.

So there is nothing particular we would need to do in the C++ lib.

But, yes, it would be great if the build systems looked for the SSL lib and used it if found, otherwise deferred to the non-SSL version.

**Comment by fpagliughi** [comment]
The C library will now report if you try to make an SSL connection with a non-SSL version of the lib.
https://github.com/eclipse/paho.mqtt.c/issues/251

I will soon remove the SSL conditional compilation from the source and always compile in the SSL components. I will also update the build systems to always link in the `ssl_options` class/cpp file.

For now, the builds will still have the SSL/non-SSL option, but it will only act to decide which version of the C library that should be linked. 

In the near future, we might want to change the build systems so that they default to the SSL version (but can opt to turn it off), or that they should look for the presence of the SSL version of the C library and use it by default. Only if it (the "as" lib) is not found, but the non-SSL version (the "a" lib) is found, then the build should default to non-SSL.

**Comment by fpagliughi** [comment]
I removed the conditional compilation and changed the builds so that they will default to SSL unless explicitly turned off.

@guilhermeferreira  if you have time, could you review and determine that I didn't do anything stupid in the autotools or CMake builds.
a5dbb7a7709c7daafbe9414c2fcef9856f646706

**Comment by guilhermeferreira** [comment]
@fpagliughi it seems fine, but give me tomorrow to take a closer look at the office. Today I'm on vacation.

**Comment by guilhermeferreira** [comment]
@fpagliughi I tested and I've read more carefully. I haven't seen anything wrong.

**Comment by guilhermeferreira** [comment]
Hey @fpagliughi 

> In the near future, we might want to change the build systems so that they default to the SSL version (but can opt to turn it off), or that they should look for the presence of the SSL version of the C library and use it by default. Only if it (the "as" lib) is not found, but the non-SSL version (the "a" lib) is found, then the build should default to non-SSL.

Please check if the PR #109 is what you had in mind. The idea is that the SSL support in Paho MQTT C++ is the same as in Paho MQTT C installed on the user system.
